version: "3"
services:
  clinics-service-prod:
    container_name: clinics-service-production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
 