version: "3"
services:
  clinics-service-dev:
    container_name: clinics-service-development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
 